version: '3.8'
services:
  # Base de datos para ms-clientes
  mysql-personas:
    image: mysql:8.0.33
    container_name: mysql-clientes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_personas
    ports:
      - "3307:3306"
    networks:
      - banking-network

  # Base de datos para ms-cuentas-movimientos
  mysql-cuentas:
    image: mysql:8.0.33
    container_name: mysql-cuentas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_cuentas
    ports:
      - "3308:3306"
    networks:
      - banking-network

  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - banking-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - banking-network

  # Microservicio de Clientes
  ms-personas:
    build: ./reto-persona
    container_name: reto-persona
    depends_on:
      - mysql-personas
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clientes:3306/banking_personas?serverTimezone=America/Guayaquil
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - banking-network

  # Microservicio de Cuentas y Movimientos
  ms-cuentas:
    build: ./reto-cuenta
    container_name: reto-cuenta
    depends_on:
      - mysql-cuentas
      - kafka
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cuentas:3306/banking_cuentas?serverTimezone=America/Guayaquil
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge
